<a href="https://colab.research.google.com/github/reynardwijaya/SC/blob/main/SC_PRAKTIK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*ubah urutan data*

In [3]:
print ("Heloo")

Heloo


Time (tampilan)

In [ ]:
import time

In [ ]:
print(time.ctime()) #time: library, c.time = function

In [7]:
#cara declare variabel ga perlu defined tipe data
x = 1
#cara print x
print(x)
x

1


1

In [14]:
x = "hello world" #string
b = 20 #int
c = 20.8 #float
f = ["apple", "berry"] #list

x, b, c, f

('hello world', 20, 20.8, ['apple', 'berry'])

In [17]:
#casting tipe var
o = int(1)   # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3
j = str(3.0)  # z will be '3.0'
print (o, y, z, j)


1 2 3 3.0


In [24]:
#gabungin string (concat)
a = "Hello"
b = "World"
c = a + b
print(c)

HelloWorld


In [19]:
a = "Hello, World!"
print(a[1])


e


In [ ]:
#size
a = "Hello, World!"
print(len(a))

In [21]:
#slicing
#Get the characters from position 2 to position 5 (not included):
b = "Hello, World!"
print(b[2:5])

#Get the characters from the start to position 5 (not included):
c = "Hello, World!"
print(c[:5])

#Get the characters from position 2, and all the way to the end:
d = "Hello, World!"
print(d[2:])

d = "Hello, World!"
print(d[-2:])

llo
Hello
llo, World!


In [23]:
a = "Hello, World!"
print(a.upper())

b = "Hello, World!"
print(b.lower())

a = "Hello, World!"
print(a.replace("H", "J"))

HELLO, WORLD!
hello, world!
Jello, World!


In [26]:
nama = "rey"
x = 19
string  = "Nama sya {} umur {}"

print (string.format(nama, x))

Nama sya rey umur 19


In [ ]:
# memberikan indeks pada elemen dalam iterable
for i in enumerate(nama):
    print(i)

In [27]:
def perbandingan (a,b):
  if a > b:
    print("a lebih dari b")
  elif a < b:
    print("a kurang dari b")
  else:
    print("a = b")

In [28]:
perbandingan (4,5)

a kurang dari b


In [30]:
i=1
while i<6:
  print(i)
  i+=1

1
2
3
4
5


In [32]:
i=2
for i in range(0,6):
  print (i)

0
1
2
3
4
5


In [59]:
for o in range (0, 100):
    if(o%2==1):
        print(o)
    elif(o%2==0):
        print("genap")

genap
1
genap
3
genap
5
genap
7
genap
9
genap
11
genap
13
genap
15
genap
17
genap
19
genap
21
genap
23
genap
25
genap
27
genap
29
genap
31
genap
33
genap
35
genap
37
genap
39
genap
41
genap
43
genap
45
genap
47
genap
49
genap
51
genap
53
genap
55
genap
57
genap
59
genap
61
genap
63
genap
65
genap
67
genap
69
genap
71
genap
73
genap
75
genap
77
genap
79
genap
81
genap
83
genap
85
genap
87
genap
89
genap
91
genap
93
genap
95
genap
97
genap
99


In [33]:
array = ["abc", "gfd"]

for i in array:
  print (i)

abc
gfd


In [36]:
import numpy as np
# digunakan untuk komputasi numerik.

In [37]:
x = np.array([1, 3, 4])
x

array([1, 3, 4])

In [43]:
y = np.array([[1, 3, 4], [4, 9, 4]])
y

array([[1, 3, 4],
       [4, 9, 4]])

In [56]:
k = np.array([[1, 0, 8], [1, 3, 4]])
k

array([[1, 0, 8],
       [1, 3, 4]])

In [57]:
print(y+k)

[[ 2  3 12]
 [ 5 12  8]]


In [47]:
def sum(a,b,c):
  sum = a+b+c
  return sum

In [48]:
  print(sum(1,2,3))

6


In [55]:
def operasi(a,b,op):
  if op=='+':
    return a+b
  elif op=='-':
    return a-b

In [52]:
print(operasi(3,2,'-'))

1


In [58]:
data = np.array([10, 20, 30, 40, 50])

print("Rata-rata:", np.mean(data))
print("Maksimum:", np.max(data))
print("Minimum:", np.min(data))
print("Standar Deviasi:", np.std(data))

Rata-rata: 30.0
Maksimum: 50
Minimum: 10
Standar Deviasi: 14.142135623730951


In [60]:
def namamur(namas, umurs, index):
    nama = namas[index]   # Ambil nama sesuai indeks
    umur = umurs[index]   # Ambil umur sesuai indeks
    returnValue = {       # Simpan dalam dictionary
        'nama': nama, 'umur': umur
    }
    return returnValue    # Kembalikan dictionary


  # Data yang Digunakan
namas = ['a', 't', 'i', 'i', 'o']
umurs = [3,4,7,2,8]
for i in range(0, len(namas)-1):
    hasil = namamur(namas, umurs, i)
    print(hasil)


{'nama': 'a', 'umur': 3}
{'nama': 't', 'umur': 4}
{'nama': 'i', 'umur': 7}
{'nama': 'i', 'umur': 2}
